server:
  port: 8080

spring:
  application:
    name: hotel-gateway

  cloud:
    gateway:
      routes:
        - id: hotel-supply-service
          uri: http://localhost:8101
          predicates:
            - Path=/api/supply/**
          filters:
            - StripPrefix=1

        - id: hotel-guide-service
          uri: http://localhost:8102
          predicates:
            - Path=/api/guide/**
          filters:
            - StripPrefix=1

logging:
  level:
    root: info
    com.hotel: debug